// Generated by CoffeeScript 1.6.1
(function() {
  var bt, deleteZahlenmauer, evaluateInput, form, genZahlenmauer, nextLayer;

  deleteZahlenmauer = function() {
    var zmE, _results;
    zmE = document.getElementById('zahlenmauer');
    _results = [];
    while (zmE.hasChildNodes()) {
      _results.push(zmE.removeChild(zmE.lastChild));
    }
    return _results;
  };

  nextLayer = function(l, offset) {
    var cE, children, mE, tE, z, zmE, _i, _len, _results;
    if (offset == null) {
      offset = 0;
    }
    tE = document.createElement('div');
    tE.className = 'table';
    tE.style.position = 'relative';
    tE.style.left = offset + 'px';
    mE = document.createElement('div');
    mE.className = 'mauer';
    tE.appendChild(mE);
    zmE = document.getElementById('zahlenmauer');
    children = zmE.children;
    if (children.length === 0) {
      zmE.appendChild(tE);
    } else {
      zmE.insertBefore(tE, children[0]);
    }
    _results = [];
    for (_i = 0, _len = l.length; _i < _len; _i++) {
      z = l[_i];
      cE = document.createElement('div');
      cE.className = 'block';
      cE.appendChild(document.createTextNode(z));
      _results.push(mE.appendChild(cE));
    }
    return _results;
  };

  genZahlenmauer = function(zm) {
    var i, offset, tmp, _i, _ref, _results;
    offset = 0;
    nextLayer(zm, offset);
    _results = [];
    while (zm.length >= 2) {
      offset += 40;
      tmp = [];
      for (i = _i = 0, _ref = zm.length - 2; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        tmp[i] = zm[i] + zm[i + 1];
      }
      zm = tmp;
      _results.push(nextLayer(zm, offset));
    }
    return _results;
  };

  evaluateInput = function(form) {
    var input, z, zm, _i, _len, _ref;
    input = form.input1.value;
    zm = [];
    _ref = input.split(',');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      z = _ref[_i];
      zm.push(parseInt(z));
    }
    deleteZahlenmauer();
    return genZahlenmauer(zm);
  };

  form = document.forms[0];

  document.forms[0].onkeypress = function(e) {
    if (!e) {
      e = window.event;
    }
    if (e.keyCode === 13) {
      evaluateInput(form);
      return false;
    }
  };

  bt = document.forms[0].button;

  bt.onclick = function(e) {
    return evaluateInput(form);
  };

  evaluateInput(form);

}).call(this);
